In [20]:
from pathlib import Path, PureWindowsPath
import pandas as pd
import numpy as np

In [2]:
data_folder = Path.cwd() / "Dark Pool Data Feed/"
path_on_windows = PureWindowsPath(data_folder)
symbol = "HTHT"

In [3]:
excel_files = [file for file in data_folder.iterdir() if file.suffix == ".xlsx"]
result = pd.DataFrame()

In [25]:
for individual_excel_files in excel_files:
    data = pd.read_excel(individual_excel_files, header=0)
    result.append(data)

In [23]:
result_concat = pd.concat(result)
result_concat

,Date,Timestamp,Ticker,Volume,Price,%of30DayAvg,Notional,Message,SecurityType,Industry,...,Industry,Sector,30DayAverage,Float,EarningsDate,Unnamed: 8,% of VOL,% of VOL,Unnamed: 14,Date
0,2020-03-11,11:40:49,AAL,323500.0,15.72,0.0156,$5.0M,DARK ISOAA,Equity,Airlines/Air Freight,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,2020-03-11,12:42:59,AAL,380000.0,15.83,0.0183,$6.0M,DARK BLOCK,Equity,Airlines/Air Freight,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,2020-03-11,15:46:35,AAP,262900.0,125.62,0.2315,$33.0M,DARK AVGPRC,Equity,Retail - Automotive,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,2020-03-11,15:00:12,AAPL,155500.0,275.43,0.0033,$42.0M,DARK BLOCK,Equity,Computer Hardware & Equipment,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,2020-03-11,17:10:25,AAPL,631936.0,275.43,0.0136,$174.0M,DARK BLOCK,Equity,Computer Hardware & Equipment,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,2020-04-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Airlines/Air Freight,Transport,2032009,75,20200506,NaN,NaN,NaN,NaN,NaT
279,2020-04-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Medical Instruments & Equipment,Health Care Equipment,3760982,219,20200501,NaN,NaN,NaN,NaN,NaT
280,2020-04-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Internet & Software,IT Services & Software,1428908,80,20200526,NaN,NaN,NaN,NaN,NaT
281,2020-04-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Internet & Software,IT Services & Software,1377808,165,20200514,NaN,NaN,NaN,NaN,NaT
282,2020-04-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Shipping,Transport,3038030,579,20200520,NaN,NaN,NaN,NaN,NaT

In [47]:
filtered_results = result_concat[result_concat.Ticker == symbol]
filtered_results = filtered_results.iloc[:, :-2]
filtered_results.sort_values("Date", inplace=True)
filtered_results

          Date Timestamp Ticker    Volume   Price  %of30DayAvg Notional
214 2020-03-13  08:31:24   HTHT  250000.0  29.355       0.1200    $7.3M
215 2020-03-13  08:31:42   HTHT  250000.0  29.355       0.1200    $7.3M
216 2020-03-13  09:31:30   HTHT  350000.0  29.540       0.1680   $10.0M
217 2020-03-13  09:53:33   HTHT  198800.0  29.340       0.0954    $5.8M
218 2020-03-13  10:13:11   HTHT  278800.0  29.375       0.1338    $8.1M
239 2020-03-26  08:45:05   HTHT  300000.0  29.700       0.1148    $8.9M
158 2020-03-30  14:52:27   HTHT  192700.0  27.035       0.0725    $5.2M
166 2020-04-14  08:43:31   HTHT  200000.0  29.475       0.0713    $5.8M
188 2020-04-17  15:00:04   HTHT  336569.0  31.020       0.1221   $10.0M
189 2020-05-06  08:36:07   HTHT  152000.0  33.700       0.0705    $5.1M

In [49]:
filtered_results.to_excel("HTHT Results.xlsx", index=False)